<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>AAFC.Holos.Core</PackageId>
    <Authors>AAFC</Authors>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/holos-aafc/Holos</PackageProjectUrl>
    <RepositoryUrl>https://github.com/holos-aafc/Holos</RepositoryUrl>
    <PackageTags>holos, aafc, agriculture, ghg</PackageTags>
    <OutputType>Library</OutputType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <SccProjectName></SccProjectName>
    <SccLocalPath></SccLocalPath>
    <SccAuxPath></SccAuxPath>
    <SccProvider></SccProvider>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Content\H.Content.csproj" />
    <ProjectReference Include="..\H.Infrastructure\H.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper">
      <Version>16.1.1</Version>
    </PackageReference>
    <PackageReference Include="NuGet.Build.Tasks.Pack">
      <Version>6.11.0</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Prism.Wpf">
      <Version>9.0.537</Version>
    </PackageReference>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.7" />
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="Services\IFarmHelper.cs" />
    <Compile Remove="Calculators\Nitrogen\NitrogenInputCalculator.cs" />
    <Compile Remove="Calculators\Carbon\CarbonInputCalculator.cs" />
  </ItemGroup>
</Project>